### PR TITLE
Add version of Gillian tests that uses multi-file analysis

### PR DESCRIPTION
**Pull request by alexismarinoiu**

### CODE REVIEW

**Comment by giltho** [comment]
- [x] Check that timing hasn't changed
- [x] Remove original ones
- [x] reorganise like old ones
- [ ] Fix documentation in GillianPlatform.github.io

**Comment by giltho** [comment]
This is now out of sync with Gillian's master because Radu's changes.
The only change required here is changing the `-s` flag to `-l disabled`

**Comment by giltho** [comment]
There's something wrong it's really really really slow
image

Also, for some reason, I can't get rid of the error when I execute the entire thing using the second method. At some point it starts failing and then everything fails and I don't know why.
We should debug that tomorrow

**Comment by alexismarinoiu** [comment]
Thanks for letting me know. See what times you get with this change; I get around the same for both:
https://github.com/GillianPlatform/Gillian/pull/34

**Pull request merged**
